#!/usr/bin/env node
// scene_builder_unity.ts — the Unity export lane.
//
// The Blender lane's twin: reads the SAME seed manifest gen.ts writes and
// emits a Unity C# Editor importer. Run it in the Unity editor via the
// umbrella: vaked-mcp unity_batch VakedSceneImporter.Build
//
//   node unity3d/scene_builder.ts <manifest.json> <out>VakedSceneImporter.cs
//   unity-editor -batchmode -quit -projectPath . -executeMethod VakedSceneImporter.Build
//
// The seed is the source; Unity is a render.

import { readFileSync, writeFileSync } from 'node:fs'

function buildScript(manifest: unknown, manifestPath: string): string {
  const m = manifest as {
    seed_line?: string
    brief?: string
    payload?: { board?: number[]; width?: number }
    tiles?: number[]
    width?: number
  }
  const board = m.tiles ?? m.payload?.board ?? []
  const size = m.width ?? m.payload?.width ?? 16
  const line = m.seed_line ?? 'the constellation · 0 + 1'
  // the same hex palette as the Blender lane
  const mats = ['#0d0512', '#3a2150', '#ff6ec7', '#ff9ad5', '#b48bff', '#ffd36e', '#62e6c9', '#e8d8f0']
  const manifestConst = JSON.stringify({ manifest_path: manifestPath, seed_line: line })
  const cells = board.map((v, i) => ({ x: i % size, y: Math.floor(i / size), h: v === -1 ? 0.3 : 0.8 + (v + 1) * 0.9, c: v === -1 ? 0 : (i * 7 + (v + 1) * 3) % mats.length }))
  const cellLines = cells.map(c =>
    `        CreateBlock(root, new Vector3(${c.x}, ${c.h / 2}, ${c.y}), new Vector3(1, ${c.h}, 1), ${c.c});`
  ).join('\n')
  return `// Auto-generated by scene_builder_unity.ts — do not edit.
// seed: ${line}
// manifest: ${manifestPath}
// Run once in the Unity editor: VakedSceneImporter.Build (or the umbrella's unity_batch).
using UnityEngine;
using UnityEditor;

public static class VakedSceneImporter
{
    static readonly string[] MATS = new string[] { ${mats.map(c => `"${c}"`).join(', ')} };

    public static void Build()
    {
        var manifestJson = System.IO.File.ReadAllText(${JSON.stringify(manifestPath)});
        var root = new GameObject("VakedScene (seed-render)").transform;
        var manifestConst = ${manifestConst};
        Debug.Log("[vaked] building scene from seed " + manifestConst);
        // board cells are appended below by the generator; heights derive from trits.
        // A real importer would parse the manifest; this scaffold builds the wire.
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Cube);
        floor.name = "the floor"; floor.transform.SetParent(root, false);
        floor.transform.localScale = new Vector3(16, 0.1f, 16); floor.transform.localPosition = new Vector3(7.5f, -0.05f, 7.5f);
        ${cellLines}
        Selection.activeGameObject = root.gameObject;
        Debug.Log("[vaked] scene built — seed line " + "${line}".Substring(0, 16) + " …");
    }

    static void CreateBlock(Transform parent, Vector3 pos, Vector3 scale, int matIdx)
    {
        var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
        go.transform.SetParent(parent, false);
        go.transform.localPosition = pos;
        go.transform.localScale = scale;
        go.name = "block-" + pos.x + "-" + pos.z;
        var mat = new Material(Shader.Find("Standard"));
        mat.color = HexToColor(MATS[matIdx % MATS.Length]);
        go.GetComponent<Renderer>().sharedMaterial = mat;
    }

    static Color HexToColor(string hex)
    {
        hex = hex.TrimStart('#');
        return new Color(
            int.Parse(hex.Substring(0, 2), System.Globalization.NumberStyles.HexNumber) / 255f,
            int.Parse(hex.Substring(2, 2), System.Globalization.NumberStyles.HexNumber) / 255f,
            int.Parse(hex.Substring(4, 2), System.Globalization.NumberStyles.HexNumber) / 255f);
    }
}
`
}

function main(): void {
  const [manifestPath, outPath] = process.argv.slice(2)
  if (!manifestPath || !outPath) {
    console.error('usage: node unity3d/scene_builder.ts <manifest.json> <out>.cs')
    process.exit(1)
  }
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
  writeFileSync(outPath, buildScript(manifest, manifestPath))
  console.log(`unity importer: ${outPath}`)
  console.log(`run: unity-editor -batchmode -quit -projectPath . -executeMethod VakedSceneImporter.Build`)
}

main()
